spring:
  datasource:
    url: jdbc:mysql://47.98.151.134:3306/spring_cache
    username: root
    password: Wqs2019..
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true

